version: "3.8"

services:
  web:
    image: meitarturgeman/messages-api:latest
    platform: ${DOCKER_PLATFORM:-linux/amd64} # Default to amd64 but can be overridden
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - JWT_SECRET_KEY=your-secret-key-here
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0
