version: '3.8'
services: 
  app:
    image: meitarturgeman/messages-api:${TAG}
    ports:
      - "5000:5000"
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=my-pwd