version: '3.8'
services:
  flask:
    build:
      context: .
      dockerfile: app/Dockerfile-flask
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    volumes:
      - .:/app
    restart: always