version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-server
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.minikube:/root/.minikube
      - /usr/bin/docker:/usr/bin/docker
      - ~/.kube:/root/.kube
      - /usr:/usr
      - /lib/modules:/lib/modules
      - /etc/kubernetes:/etc/kubernetes
      - /tmp/hostpath-provisioner:/tmp/hostpath-provisioner
      - /var/lib/minikube:/var/lib/minikube
      - /var/lib/kubelet:/var/lib/kubelet
    environment:
      - JAVA_OPTS=-Xmx2g
      - KUBECONFIG=/root/.kube/config
      - MINIKUBE_HOME=/root
    restart: always
    user: root
    privileged: true
    network_mode: "host"

volumes:
  jenkins_data:
