version: '3.8'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-jenkins
    container_name: jenkins-server
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.kube:/root/.kube
      - ~/.minikube:/home/devops/.minikube
    environment:
      - JAVA_OPTS=-Xmx2g
      - KUBECONFIG=/root/.kube/config
    restart: always
    user: root
    privileged: true
    extra_hosts:
      - "minikube:192.168.49.2"

volumes:
  jenkins_data:
