version: '3.8'
services:
  jenkins:
    build:
      context: ..
      dockerfile: app/Dockerfile-jenkins
    container_name: jenkins-server
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      - JAVA_OPTS=-Xmx2g
    user: root
    privileged: true

volumes:
  jenkins_data:
