version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-server
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.minikube:/root/.minikube
      - /usr/bin/docker:/usr/bin/docker
      - ~/.kube:/root/.kube
    environment:
      - JAVA_OPTS=-Xmx2g
      - KUBECONFIG=/root/.kube/config
    restart: always
    user: root
    privileged: true

volumes:
  jenkins_data:
