apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: bXl1c2Vy                # myuser
  POSTGRES_PASSWORD: bXlwYXNzd29yZA==    # mypassword
  POSTGRES_DB: bXlkYg==                  # mydb

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  SECRET_KEY: dGVzdHNlY3JldGtleQ==   # testsecretkey
  DATABASE_URL: cG9zdGdyZXNxbDovL215dXNlcjpteXBhc3N3b3JkQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9teWRi
  # postgresql://myuser:mypassword@postgres-service:5432/mydb